import Head from 'next/head'
import Header from '@/components/globalComponents/header'
import Newsletter from '@/components/news'
import Home from '@/components/home'

export default function Main() {
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>


      <main className='main'>
        <Home/>
        <Newsletter/>
      </main>
    </div>
  )
}
